[project]
name = "quick-summaries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ollama>=0.3.3",
    "openai>=1.54.4",
    "pandas>=2.2.3",
    "pip-tools>=7.4.1",
    "tiktoken",
]
